[build]
  command = "pnpm run build:netlify"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@prisma/client-runtime-utils", ".prisma", "pg"]
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
