export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("lift_records").del();
  await knex("lift_records").insert([
    {
      id: "1",
      lift_id: "1",
      weight: 120,
      date: Date.now().toString(),
      user_id: "rory",
      is_max: true,
    },
    {
      id: "2",
      lift_id: "1",
      weight: 100,
      date: "2025-01-13",
      user_id: "rory",
      is_max: false,
    },
    {
      id: "3",
      lift_id: "1",
      weight: 110,
      date: "2025-02-21",
      user_id: "rory",
      is_max: false,
    },
    {
      id: "4",
      lift_id: "3",
      weight: 100,
      date: "2024-11-01",
      user_id: "rory",
      is_max: false,
    },
    {
      id: "5",
      lift_id: "3",
      weight: 140,
      date: "2025-01-05",
      user_id: "rory",
      is_max: true,
    },
    {
      id: "6",
      lift_id: "3",
      weight: 110,
      date: "2024-11-01",
      user_id: "rory",
      is_max: false,
    },
    {
      id: "7",
      lift_id: "4",
      weight: 180,
      date: "2025-03-01",
      user_id: "rory",
      is_max: true,
    },
    {
      id: "8",
      lift_id: "4",
      weight: 100,
      date: "2025-03-15",
      user_id: "rory",
      is_max: false,
    },
    {
      id: "9",
      lift_id: "4",
      weight: 90,
      date: "2025-04-03",
      user_id: "rory",
      is_max: false,
    },
    {
      id: "10",
      lift_id: "5",
      weight: 65,
      date: "2024-12-15",
      user_id: "rory",
      is_max: false,
    },
    {
      id: "11",
      lift_id: "5",
      weight: 80,
      date: "2024-12-17",
      user_id: "rory",
      is_max: false,
    },
    {
      id: "12",
      lift_id: "5",
      weight: 100,
      date: "2025-04-10",
      user_id: "rory",
      is_max: true,
    },
    {
      id: "13",
      lift_id: "1",
      weight: 120,
      date: Date.now().toString(),
      user_id: "salla",
      is_max: true,
    },
    {
      id: "14",
      lift_id: "1",
      weight: 100,
      date: "2025-01-13",
      user_id: "salla",
      is_max: false,
    },
    {
      id: "15",
      lift_id: "1",
      weight: 110,
      date: "2025-02-21",
      user_id: "salla",
      is_max: false,
    },
    {
      id: "16",
      lift_id: "3",
      weight: 100,
      date: "2024-11-01",
      user_id: "salla",
      is_max: false,
    },
    {
      id: "17",
      lift_id: "3",
      weight: 140,
      date: "2025-01-05",
      user_id: "salla",
      is_max: true,
    },
    {
      id: "18",
      lift_id: "3",
      weight: 110,
      date: "2024-11-01",
      user_id: "salla",
      is_max: false,
    },
    {
      id: "19",
      lift_id: "4",
      weight: 180,
      date: "2025-03-01",
      user_id: "salla",
      is_max: true,
    },
    {
      id: "20",
      lift_id: "4",
      weight: 100,
      date: "2025-03-15",
      user_id: "salla",
      is_max: false,
    },
    {
      id: "21",
      lift_id: "4",
      weight: 90,
      date: "2025-04-03",
      user_id: "salla",
      is_max: false,
    },
    {
      id: "22",
      lift_id: "5",
      weight: 65,
      date: "2024-12-15",
      user_id: "salla",
      is_max: false,
    },
    {
      id: "23",
      lift_id: "5",
      weight: 80,
      date: "2024-12-17",
      user_id: "salla",
      is_max: false,
    },
    {
      id: "24",
      lift_id: "5",
      weight: 100,
      date: "2025-04-10",
      user_id: "salla",
      is_max: true,
    },
  ]);
}
